version: "3"

networks:
  test-infrastructure-network:
    driver: bridge

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres-xmltest
    networks:
      - test-infrastructure-network
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5455:5432'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d


# sudo docker-compose -f docker-compose.yml up